kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: "jws-example"
  annotations:
    description: Defines how to deploy the application server
    template.alpha.openshift.io/wait-for-ready: 'true'
spec:
  strategy:
    type: Rolling
  triggers:
  - type: ImageChange
    imageChangeParams:
      automatic: true
      containerNames:
      - jws-example
      from:
        kind: ImageStreamTag
        name: "jws-example:latest"
  - type: ConfigChange
  replicas: {{ .Values.replicaCount }}
  selector:
    name: "jws-example"
  template:
    metadata:
      name: "jws-example"
      labels:
        name: "jws-example"
        test: {{ template "test" . }}
        othertest: {{ .Values.test }}
    spec:
      containers:
      - name: jws-example
        image: " "
        ports:
        - containerPort: 8080
        readinessProbe:
          timeoutSeconds: 3
          initialDelaySeconds: 3
          httpGet:
            path: "/health"
            port: 8080
        livenessProbe:
          timeoutSeconds: 3
          initialDelaySeconds: 30
          httpGet:
            path: "/health"
            port: 8080
        env:
        - name: KUBERNETES_NAMESPACE
          value: "jbosswebserver" 
        resources:
          limits:
            memory: "512Mi"
