kind: Service
apiVersion: v1
metadata:
  name: "jbosswebserver"
  annotations:
    description: DNS service for clustering.
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: web
    port: 8080
    targetPort: 8080
  selector:
    name: "jws-example"
