kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name:  {{ .Values.applicationName | quote }}
spec:
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: {{ .Values.applicationName }}
