kind: Service
apiVersion: v1
metadata:
  name: "jws-example"
  annotations:
    description: Exposes and load balances the application pods
spec:
  ports:
  - name: web
    port: 8080
    targetPort: 8080
  selector:
    name: "jws-example"
